import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
const logs = [];
page.on('console', (m) => { logs.push(m.type() + ': ' + m.text().slice(0, 900)); });
page.on('pageerror', (e) => logs.push('PAGEERR: ' + (e.message || '').slice(0, 900)));
await page.goto('http://127.0.0.1:3000/', { waitUntil: 'load', timeout: 30000 });
await page.waitForTimeout(4000);
for (const l of logs.filter((l) => !l.includes('Failed to load resource'))) console.log(l);
await browser.close();
