import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
page.on('pageerror', e => errs.push((e.message || '').slice(0, 250)));
page.on('console', m => { if (m.type() === 'error') errs.push('[console] ' + m.text().slice(0, 250)); });
const before = page.url();
await page.goto('http://localhost:3000/', { waitUntil: 'load', timeout: 120000 });
await page.waitForTimeout(9000);
const after = page.url();
console.log('url:', after);
const headTxt = await page.evaluate(() => document.body ? (document.body.innerText || '').slice(0, 120).replace(/\n/g, ' | ') : '(empty)');
console.log('body:', headTxt);
console.log('appErrorText:', await page.evaluate(() => /Application error: a client-side exception/i.test(document.body ? document.body.innerText : '')));
console.log('$$typeof error:', errs.some(x => x.includes("$$typeof")));
console.log('all page errors:', JSON.stringify(errs.slice(0, 8)));
console.log('url changed:', before !== after);
await browser.close();