// StillCraft client copy, seeded as file-based content overrides (no DB needed).
// Same shape as DB rows: { el_id, kind, value, orig_html }. Applied via applyOverrides
// (static replace + unique-gated flight patch), so hydration keeps the new copy.
const T = (el_id, value, orig_html) => ({ el_id, kind: 'text', value, orig_html });

// Page-scoped whole-value flight replacements. Applied AFTER flight IA + overrides.
// Safe only when EVERY whole-value occurrence on that page wants the same new value
// (short origs like "Branding" never pass patchFlight's uniqueness gate, so they need this).
export const FLIGHT = {
  '/service/exhibits': [
    [`Exhibits`, `Mall and Retail`],
    [`Branding`, `Eight Years Running Calendars`],
    [`Concept & Design`, `One Team From Planning To The Floor`],
    [`Complex Logistics`, `Built Around Your Tenant Mix`],
    [`Hybrid & Digital Content`, `Every Season Closes With A Report`],
    [`Construction`, `Vendor Managed`],
    [`Technical Production`, `Staffed By Us`],
    [`Guest Experience & Activations`, `Reported Each Season`],
  ],
  '/service/events': [
    [`Events`, `Brand Activations`],
    [`Concept & Design`, `Eight Years Delivering`],
    [`Branding`, `Your Strategist Is Your Producer`],
    [`Hybrid & Digital Content`, `Built Around Your Audience`],
    [`Construction`, `Relationships That Compound`],
    [`Technical Production`, `Every Engagement Closes With A Report`],
    [`Complex Logistics`, `Reach And Proximity`],
    [`Guest Experience & Activations`, `One Team Accountable`],
  ],
  '/service/congresses': [
    [`Congresses`, `Mall Space Monetization`],
    [`Concept & Design`, `Assessment & Curation`],
    [`Branding`, `Vendor Sourcing`],
    [`Hybrid & Digital Content`, `Activation & Fit-Out`],
    [`Construction`, `Live Management`],
    [`Technical Production`, `Handoff or Renewal`],
    [`Complex Logistics`, `Hybrid Revenue Model`],
    [`Guest Experience & Activations`, `Reported Outcomes`],
    [`Where minds meet, decision move.`, `When an anchor tenant exits, StillCraft steps in to run the space.`],
    [`create your moment`, `The Problem.`],
    [`congress moment`, `your empty unit could earn.`],
    [`Plan your next congress`, `Talk to us about vacant unit`],
  ],
};

export const CONTENT = {
  '/': [
    // Hero description (anchor row: the template hero subline has no stable
    // id). The old t-1/t-2 ID rows targeted the header ContactMenu button
    // after a re-tag drifted ids — removed so the button label restores.
    { el_id: 'ahome-hero', kind: 'text', tag: 'DIV', idx: 0,
      value: `StillCraft started with a simple observation: malls needed more than events, they needed programming that gave people a reason to come, stay, and return. Brands needed more than activations that looked good in a recap deck, they needed experiences people could actually feel and remember. And corporate teams needed environments that reflected the kind of culture, connection, and impression they wanted to create. Rather than choose one lane, we built StillCraft to work across all three.`,
      orig_html: `Designed to be remembered.<br class="css-0">We build experiences that audiences feel, not just attend.` },
  ],
  '/about': [
    T('t-77', `The People Behind`, `Our secret?`),
    T('t-78', `Eight Years Of Delivery`, `The people`),
    T('t-21', `Eight years of turning footfall and attention into results.`, `About Iventions`),
    T('t-24', `Most agencies choose a lane and stay in it. A media house that buys airtime. An events company that builds stages. A consultancy that writes strategy decks and hands them off to someone else to build. StillCraft chose not to. For eight years we have worked across shopping malls, brands, and corporate teams, planning the thinking and doing the building, without splitting the two apart.`, `Meet StillCraft Events, the global event agency behind powerful brand moments an`),
    // NOTE: no t-25 row — ids drifted onto the Showreel video label; the old
    // row stuffed body copy into the video control. Body paras 2-3 have no
    // template element; the story is carried by header/values/team/stats.
  ],
  '/service/exhibits': [
    T('t-21', `Mall and Retail`, `Exhibits`),
    T('t-24', `One calendar, run for you.`, `We make exhibits`),
    T('t-25', `Not just`, `impossible to`),
    T('t-26', `planned.`, `ignore.`),
    T('t-28', `Entertainment Programmes: recurring activations across Creative Economy, Family Entertainment, STEM and Wellness, sourced, staffed and run by us.`, `We design brand spaces with purpose`),
    T('t-30', `Seasonal Calendar: seven annual moments planned a year ahead of the retail curve.`, `We create experiences that captivate`),
    T('t-32', `Shop Launches and Tenant Support: opening-day moments plus ongoing tenant coordination.`, `We deliver with flawless precision`),
    T('t-33', `The team that stays accountable for the whole calendar.`, `We design exhibit spaces that perform`),
    T('t-34', `Eight Years Running Calendars`, `Branding`),
    T('t-35', `One Team From Planning To The Floor`, `Concept & Design`),
    T('t-36', `Built Around Your Tenant Mix`, `Complex Logistics`),
    T('t-37', `Every Season Closes With A Report`, `Hybrid & Digital Content`),
    T('t-38', `Vendor Managed`, `Construction`),
    T('t-39', `Staffed By Us`, `Technical Production`),
    T('t-40', `Reported Each Season`, `Guest Experience & Activations`),
    T('t-41', `Eight Years Running Calendars`, `Branding`),
    T('t-42', `One Team From Planning To The Floor`, `Concept & Design`),
    T('t-43', `Built Around Your Tenant Mix`, `Complex Logistics`),
    T('t-44', `Every Season Closes With A Report`, `Hybrid & Digital Content`),
    T('t-45', `Vendor Managed`, `Construction`),
    T('t-46', `Staffed By Us`, `Technical Production`),
    T('t-47', `Reported Each Season`, `Guest Experience & Activations`),
    T('t-67', `What The Programme Moves`, `Projects you might also be interested in`),
    T('t-68', `FOOTFALL`, `01`),
    T('t-69', `DWELL TIME`, `02`),
    T('t-70', `TENANT SALES`, `03`),
    T('t-119', `Mall programming answers`, `Experts Answers`),
    T('t-120', `What does StillCraft take off our plate?`, `What does a trade show marketing agency like Iventions deliver at exhibitions?`),
    T('t-121', `Staffing, vendor management and delivery of the full calendar, built to work with your tenant mix. Your team manages the center instead of managing a calendar.`, `A full-service trade show marketing agency designs, produces and manages brand experiences for exhibitions and trade shows. From 3D stand design and graphic production to on-site project management, AV, staffing and activations, every detail is carefully engineered so brands can perform at their best on the show floor.`),
    T('t-122', `How is the calendar built?`, `Is Iventions a trade show marketing company that handles both design and production?`),
    T('t-123', `Every calendar starts with your center's actual traffic patterns and tenant mix. The team that builds it is the same team that staffs and runs it, so nothing gets lost between proposal and delivery.`, `Yes. Iventions is a trade show marketing company with an in-house design and production team. This integrated setup allows full control over quality, timelines and budgets from concept to delivery, keeping the process seamless, efficient and stress-free.`),
    T('t-124', `What are the eight moments?`, `Can exhibition stands be delivered anywhere in Europe?`),
    T('t-125', `New Year, Valentine's, Easter Weekend, Mother's Day, Father's Day, Back to School, Halloween and Christmas -- mapped to the year before the year starts.`, `Yes. While based in Barcelona and London, Iventions delivers projects across Europe. With experience in major exhibition venues, trusted local suppliers and a multilingual team with global know-how, international trade shows are managed smoothly and confidently from start to finish.`),
    T('t-126', `How do we know it worked?`, `What exhibition and trade show services are offered?`),
    T('t-127', `Every season closes with a report. At Galleria Mall, a Father's Day activation delivered a 30% lift in footfall, 22% in dwell time and 17% in tenant sales.`, `Iventions provides a complete end-to-end service covering 3D exhibition stand design, graphic design and branding, stand production and build, audiovisual and technical solutions, hosts and brand ambassadors, interactive activations, logistics, installation, dismantling and on-site project management. All services are integrated under one trade show marketing company to ensure consistency, clarity and quality throughout the project.`),
    T('t-128', `Who runs it on the day?`, `Why choose Iventions as a trade show marketing company?`),
    T('t-129', `We do. StillCraft plans, staffs and runs the entire calendar -- the calendar approved in January is the one delivered in December.`, `Iventions combines strategic thinking, creative design and flawless execution. With in-house capabilities, international experience and a true partnership mindset, the team helps brands stand out, perform and stay memorable at trade shows across Europe.`),
    T('t-130', `Let's take the`, `Let’s build your`),
    T('t-131', `calendar off`, `brand’s next`),
    T('t-132', `your plate`, `showstopper`),
    T('t-133', `Tell us about your shopping mall and what this year's calendar still needs. We'll come back with a plan, and a team that runs it, not just proposes it.`, `From bold ideas to flawless execution, we design exhibit spaces that grab attention and keep it. Let’s create something people won’t just walk past, but talk about.`),
  ],
  '/service/events': [
    T('t-21', `Brand Activations`, `Events`),
    T('t-24', `Strategy through delivery.`, `We bring people into`),
    T('t-25', `One team, one brand,`, `the moment, and make`),
    T('t-26', `one bond with your audience.`, `it last.`),
    T('t-28', `REACH:`, `Built on brand,`),
    T('t-29', `Above The Line (ATL) -- campaigns, sponsorships and launch moments at national reach.`, `made to move`),
    T('t-31', `PROXIMITY:`, `Moments that hit`),
    T('t-32', `Below The Line (BTL) -- activations, roadshows and corporate environments in people's hands.`, `different`),
    T('t-34', `CONSULT - PLAN -`, `Precision at any`),
    T('t-35', `PRODUCE - REPORT, one team end to end.`, `scale`),
    T('t-36', `Why Brands Bring Us In`, `We design event spaces that hit every beat`),
    T('t-37', `Eight Years Delivering`, `Concept & Design`),
    T('t-38', `Your Strategist Is Your Producer`, `Branding`),
    T('t-39', `Built Around Your Audience`, `Hybrid & Digital Content`),
    T('t-40', `Relationships That Compound`, `Construction`),
    T('t-41', `Every Engagement Closes With A Report`, `Technical Production`),
    T('t-42', `Reach And Proximity`, `Complex Logistics`),
    T('t-43', `One Team Accountable`, `Guest Experience & Activations`),
    T('t-44', `Eight Years Delivering`, `Concept & Design`),
    T('t-45', `Your Strategist Is Your Producer`, `Branding`),
    T('t-46', `Built Around Your Audience`, `Hybrid & Digital Content`),
    T('t-47', `Relationships That Compound`, `Construction`),
    T('t-48', `Every Engagement Closes With A Report`, `Technical Production`),
    T('t-49', `Reach And Proximity`, `Complex Logistics`),
    T('t-50', `One Team Accountable`, `Guest Experience & Activations`),
    T('t-115', `Brand answers`, `Experts Answers`),
    T('t-116', `What does StillCraft do for brands?`, `What does an event marketing agency like Iventions deliver for brands?`),
    T('t-117', `StillCraft plans a brand's next move and stays on to deliver it, from the boardroom to the ground. No handoffs between strategist and producer, no brief reinterpreted by three vendors. One team, accountable for the relationship your brand builds with its audience.`, `An event marketing agency plans, designs and delivers experiences that connect people with brands in meaningful ways. At Iventions, this means shaping the strategy, creative concept and guest journey, then executing every detail, from venue selection to on-site delivery, so events feel seamless, impactful and memorable.`),
    T('t-118', `What is the ATL and BTL mix?`, `Is Iventions an event management company that handles everything end to end?`),
    T('t-119', `Reach puts the brand in front of the audience that matters at scale: media campaigns, sponsorships, large format and OOH, launch events. Proximity puts it in their hands: experiential activations, roadshows and sampling, in-person promotions, corporate environments.`, `Yes. Iventions is a full-service event management company that takes care of the entire process. From strategy and creative direction to production, logistics, project management and on-site setup, everything is handled under one roof with a single point of contact.`),
    T('t-120', `How does an engagement run?`, `Can an event be delivered anywhere in Europe?`),
    T('t-121', `Consult, then plan, then produce, then report. One team maps media and placements alongside activations and environments around a single idea, and closes with a report on reach, engagement and sentiment.`, `Absolutely. Although based in Barcelona and London, Iventions delivers events across Europe and beyond. With extensive international experience, trusted local suppliers and a multilingual team with global expertise, events are executed smoothly regardless of location.`),
    T('t-122', `Which mix is right for us?`, `What types of events does an event management company like Iventions produce?`),
    T('t-123', `Start with the audience: what they need to feel about the brand, and what it will take to earn that. We recommend ATL, BTL or a blend of both before anything gets built.`, `Iventions delivers a wide range of events, including brand experiences, corporate events, product launches, summits, conferences and immersive experiences. Each project is tailored to the ambition behind it, combining creativity with flawless execution.`),
    T('t-124', `Why bring StillCraft in?`, `Why choose Iventions as an event marketing agency?`),
    T('t-125', `Eight years planning and producing brand marketing under one roof. The idea that gets attention is the same idea that earns trust once your audience is standing in front of you.`, `Iventions combines strategic thinking, creative ambition and meticulous execution. With a partnership mindset, international reach and obsessive attention to detail, the team turns complex ideas into effortless experiences, placing brands and people exactly where they belong: in the spotlight.`),
    T('t-126', `Lets discuss`, `No ordinary events.`),
    T('t-127', `your next`, `Only spotlight`),
    T('t-128', `activation!`, `moments.`),
    T('t-129', `Tell us about your brand and what you're looking to activate. We'll come back with a recommendation on the right mix of reach and proximity, and a team that can deliver both.`, `Every square meter we build is intentional, crafted to impress, engineered to connect, and built for the brands that play on the global stage.`),
  ],
  '/contact': [
    T('t-53', `reaching out we're here, ready to listen. Email info@stillcraftevents.co.ke`, `reaching out we’re here, ready to listen`),
    T('t-54', `Call +254 792 234 337 or +254 755 959 236. Visit Piedmont, 671 Ngong Road, Nairobi, Kenya. Let's connect.`, `and respond with purpose. Let’s connect.`),
  ],
  '/service/congresses': [
    T('t-21', `Mall Space Monetization`, `Congresses`),
    T('t-22', `The Problem.`, `create your moment`),
    T('t-23', `The Problem.`, `create your moment`),
    T('t-24', `When an anchor tenant exits, StillCraft steps in to run the space.`, `Where minds meet, decision move.`),
    T('t-26', `Assessment & Curation`, `We define the vision`),
    T('t-28', `Vendor Sourcing`, `We shape the experience`),
    T('t-30', `Live Management`, `We deliver with precision`),
    T('t-31', `Kenya's mall sector has been repeatedly hit by anchor tenant collapses, leaving large vacant units behind. A dark anchor drags the whole property down with it. Nobody is running the vacant unit itself, day to day, as a working, earning space while a permanent tenant is found. StillCraft steps in to run it as a managed occupation of your space — not an event.`, `We design congress spaces that command attention`),
    T('t-32', `Assessment & Curation`, `Concept & Design`),
    T('t-33', `Vendor Sourcing`, `Branding`),
    T('t-34', `Activation & Fit-Out`, `Hybrid & Digital Content`),
    T('t-35', `Live Management`, `Construction`),
    T('t-36', `Handoff or Renewal`, `Technical Production`),
    T('t-37', `Hybrid Revenue Model`, `Complex Logistics`),
    T('t-38', `Reported Outcomes`, `Guest Experience & Activations`),
    T('t-39', `Assessment & Curation`, `Concept & Design`),
    T('t-40', `Vendor Sourcing`, `Branding`),
    T('t-41', `Activation & Fit-Out`, `Hybrid & Digital Content`),
    T('t-42', `Live Management`, `Construction`),
    T('t-43', `Handoff or Renewal`, `Technical Production`),
    T('t-44', `Hybrid Revenue Model`, `Complex Logistics`),
    T('t-45', `Reported Outcomes`, `Guest Experience & Activations`),
    T('t-82', `What happens to a mall when an anchor tenant leaves?`, `What do corporate conference planning services include for a professional congress?`),
    T('t-83', `A dark anchor drags the whole property down with it. Foot traffic near it drops, and some smaller tenants can invoke lease clauses to reduce or exit their own rent once anchor occupancy falls below a set threshold. (Occupancy figures for Nairobi malls vary and should be treated as estimates until sourced.)`, `Corporate conference planning services cover the full design and delivery of professional conferences, from strategic thinking to flawless execution. At StillCraft Events Co., this includes creative concept development, guest journey design, venue scouting, technical planning, project management and on-site delivery, ensuring conferences feel seamless, engaging and purpose-driven.`),
    T('t-84', `Who runs the vacant unit while it waits for a permanent tenant?`, `Are corporate conferences managed end to end, from strategy to on-site execution?`),
    T('t-85', `Real estate and leasing firms handle landing a new permanent anchor. Event companies handle short, one-off activations. StillCraft steps in to run the space itself, day to day, as a working, earning programme — curated, managed and reported on — until it is properly relet.`, `Yes. StillCraft Events Co. manages conferences end to end. From defining objectives and shaping the creative direction to coordinating suppliers, schedules and on-site setup, everything is handled through one integrated process with a single point of contact.`),
    T('t-86', `What does running the space involve?`, `Is full technical production included in corporate conference planning services?`),
    T('t-87', `Assessment and curation of the space against the tenant mix, vendor sourcing on short-term commercial terms, lightweight reversible fit-out, then ongoing live management typically one to six months, closing with handoff or renewal on the strength of the track record.`, `Absolutely. The technical side of the congress is fully managed, including content scripting, room layouts, stage design, audiovisual production and technical coordination. Every technical decision is made to support clarity, flow and the overall attendee experience.`),
    T('t-88', `How does StillCraft charge for this?`, `Can a congress be delivered anywhere in Europe?`),
    T('t-89', `Hybrid — a smaller retainer plus a performance bonus tied to footfall or revenue targets.`, `Yes. While based in Nairobi and London, StillCraft Events Co. delivers congresses across Europe and beyond. With international experience, trusted local partners and a multilingual team, conferences are executed smoothly across different countries, venues and cultural contexts.`),
    T('t-90', `Why is StillCraft the team for this?`, `Why choose StillCraft Events Co. for corporate conference planning services?`),
    T('t-91', `StillCraft already curates and runs physical activations and reports outcomes back to mall clients. This is a natural extension of that work, not a new business — internationally proven by programmes like Primaris REIT and the pop-up curation agencies abroad.`, `StillCraft Events Co. combines strategic clarity, creative thinking and meticulous execution. With international experience, in-house expertise and a partnership mindset, the team delivers conferences that feel effortless to organise and meaningful to attend, placing ideas, speakers and audiences exactly where they belong: in the spotlight.`),
    T('t-92', `Let's find out what `, `Let's create your `),
    T('t-93', `your empty unit could earn.`, `congress moment`),
    T('t-94', `Start with one space. We'll assess it, propose a concept, and show you what it could generate before anything is signed.`, `From strategic planning and destination expertise to flawless on-site delivery, we design congresses that leave nothing to chance. Your audience won't just attend. They'll remember.`),
    T('t-95', `Talk to us about vacant unit`, `Plan your next congress`),
    T('t-96', `Talk to us about vacant unit`, `Plan your next congress`),
  ],
  
  '/privacy-policy': [
    T('t-41', `While using our Website, we may request your personal information, such as your email address, phone number and name. Upon your express acceptance we may use this data to send you newsletters or share marketing materials that may be of interest to you. You can opt out of receiving such communications from us at any time by emailing us at&nbsp;<a data-sc-id="t-42" href="mailto:info@stillcraftevents.co.ke">info@stillcraftevents.co.ke</a>.`, `While using our Website, we may request your personal information, such as your email address, phone number and name. Upon your express acceptance we may use this data to send you newsletters or share marketing materials that may be of interest to you. You can opt out of receiving such communications from us at any time by emailing us at&nbsp;<a data-sc-id="t-42" href="mailto:info@iventions.com">info@iventions.com</a>.`),
    T('t-46', `The entity responsible for processing personal data collected on this website is StillCraft Events Co., with office at Piedmont, 671 Ngong Road, Nairobi, Kenya. You can contact us at +254 792 234 337 or by emailing info@stillcraftevents.co.ke`, `The entity responsible for processing personal data collected on this website is Iventions International Events, S.L.U., identified by tax identification number B65280398 , with address in Av. Diagonal 433, 4-2, Barcelona, Spain. You can contact us at the number +34 933 028 640 or emailing us to info@iventions.com`),
  ],
  '/cookie-policy': [
    T('t-33', `WHY DOES STILLCRAFT USE THESE COOKIES?`, `WHY DOES IVENTIONS USE THESE COOKIES?`),
    T('t-34', `The use of Cookies allows us to:`, `The use of Cookies allows us to:`),
  ],
};
