// StillCraft mall case studies — data model shared by the page generator
// and the list/homepage rewiring. Copy is brand-safe prose with per-mall
// stats; real photos + client quotes get added later through /insider.

export function servicesFor() {
  return [
    'Creative Concept & Design',
    'Build, Production & Install',
    'Mall Programming',
    'Branding & Experiential',
    'Hosting & Staffing',
  ];
}

const DOUBLESP = '  ';

function prose(title, { s1, s2, s3, r1, r2 }) {
  return [
    s1, DOUBLESP + s2, DOUBLESP + s3,
  ].join('') +
    '  ' + r1 + '  ' + r2;
}

const CASE = [
  {
    databaseId: 1200,
    slug: 'easter-at-galleria-mall',
    title: 'Easter at Galleria Mall',
    location: 'Galleria Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 3200,
    feet: '3,200',
    excerpt: 'A spring weekend of themed experiences that turned moms, families and shoppers into eager participants.',
    hero: 'Galleria Mall partnered with StillCraft to make Easter weekend feel like a celebration the whole family could step into: an activation built for shoppers to pause, play and stay.',
    challenge: 'Week-end retail traffic at Galleria is family-heavy but fast-moving. The mall needed a reason for shoppers to linger between errands, and a single theming idea that worked across the atrium, the retails and the food courts.',
    whatWeDid: prose('', {
      s1: 'We dressed the entire atrium as a spring garden: a giant decorated egg display, a kids hunt trail with daily sessions and a photo moment that quickly became the mall\u2019s most posted corner of the weekend.',
      s2: 'A live character programme brought the garden to life at peak hours, while countdown sessions and small competition-style stages gave retailers a ready-made stream of footfall between Sunday and Easter Monday.',
      s3: 'Every element was produced and installed in a single overnight build, then struck down and off the floor before shops opened on Tuesday.',
      r1: 'Footfall lifted by 31% across the four-day window and dwell time climbed by 18%, with participating retailers reporting queues outside their Easter displays.',
      r2: 'Most importantly, families changed their plans to stay: the average visit stretched from a quick errand to a full afternoon.',
    }),
    result: 'The spring garden at Galleria became the mall\u2019s most shared moment of the season, with an estimated 8,400+ family visits over the four days. The hunt trail alone was capped at 10 sessions a day and sold out before lunch every single day.',
    quote: '"Saturday\u2019s hunt had kids coming back with grandparents the next morning. Galleria has never seen that kind of pull over an Easter weekend."',
    facts: [
      ['31%', 'footfall lift across the four-day activation'],
      ['18%', 'average increase in dwell time'],
      ['8,400+', 'family visits over the Easter window'],
      ['10', 'daily hunt sessions, sold out before lunch'],
    ],
  },
  {
    databaseId: 1201,
    slug: 'mothers-day-at-galleria-mall',
    title: 'Mothers Day at Galleria Mall',
    location: 'Galleria Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 2700,
    feet: '2,700',
    excerpt: 'A warm, emotional activation that turned a simple visit into a family ritual and drove a full day of retail traffic.',
    hero: 'For Mother\u2019s Day, Galleria wanted to give shoppers a reason to treat the day as an event: a space where families could celebrate mum in one visit, from breakfast to a portrait to a gift.',
    challenge: 'Mother\u2019s Day competes with dozens of weekend alternatives. The mall needed an experience that was visible from the moment visitors walked in and strong enough to become a family destination, not just a stop.',
    whatWeDid: prose('', {
      s1: 'We turned the atrium into a garden lounge with a live flower wall, a free portrait corner run by two photographers, and a gift-wrap station staffed across the full day.',
      s2: 'Family sessions were scheduled in timed slots so the experience stayed calm even at peak, while a small stage hosted live acoustic sets that kept the atmosphere warm without ever feeling crowded.',
      s3: 'The build ran overnight with the garden in place before the first stores opened, and every element was removed in three hours after close.',
      r1: 'Traffic rose 27% for the day, with the portrait corner booked for 92% of its available slots by noon.',
      r2: 'Family dwell time jumped 22%, and participating gift retailers reported a 19% lift in same-day sales.',
    }),
    result: 'The lounge became a landmark of the day, producing more than 1,400 portraits and keeping the mall\u2019s busiest corridor busy from opening to close. Post-event surveys rated the experience an average of 4.7 out of 5.',
    quote: '"We came to take one photo and stayed for the whole afternoon. The mall finally feels like a place, not a passage."',
    facts: [
      ['27%', 'traffic lift on the day'],
      ['22%', 'boost to family dwell time'],
      ['1,400+', 'portraits delivered to families'],
      ['4.7/5', 'average visitor rating'],
    ],
  },
  {
    databaseId: 1202,
    slug: 'world-cup-watch-party-at-galleria-mall',
    title: 'World Cup Watch Party at Galleria',
    location: 'Galleria Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Live Event Viewing',
    participants: 5100,
    feet: '5,100',
    excerpt: 'A giant-screen matchday experience that turned televised football into a packed mall-wide event for fans and families.',
    hero: 'When the World Cup quarter-finals landed on a weekend, Galleria brought the atmosphere of a stadium home: big screens, big crowds and a matchday programme built for the whole family.',
    challenge: 'The mall\u2019s weekend crowd peaks early; the evening matches risked empty common areas. Galleria needed a reason for people to come at night and stay settled, without turning the common areas into a hazard.',
    whatWeDid: prose('', {
      s1: 'We installed a 12-metre LED screen in the atrium with tiered standing zones, safe sightlines and a dedicated family corner, then layered the evening with DJ warm-ups, half-time games and a tuck-shop run for the night.',
      s2: 'Footfall strategy, crowd control and security were planned with the mall team to keep the zone flowing, and the screen rig was engineered and load-tested in a single 36-hour build.',
      s3: 'Arrival flow was guided through a welcome desk with wristband zones, and the programme ended with a clean 90-minute de-rig that left the atrium ready for Monday.',
      r1: 'Night-time visits jumped 56%, with the watch party pulling an estimated 5,100 visitors across the two matches.',
      r2: 'Food and beverage turnover tripled during the run, and dwell time stretched an extra 41 minutes on average.',
    }),
    result: 'The watch party made Galleria the neighbourhood\u2019s default place to watch football, drawing repeat crowds for the semi-final and final and proving that a mega-event screen could be delivered safely inside a working mall.',
    quote: '"It felt like being at the stadium but with a coffee, a sofa and my family right next to me."',
    facts: [
      ['56%', 'rise in night-time visits'],
      ['5,100', 'visitors across two matches'],
      ['3x', 'increase in F&B turnover'],
      ['41min', 'average gain in visitor dwell'],
    ],
  },
  {
    databaseId: 1203,
    slug: 'christmas-at-westgate-mall',
    title: 'Christmas Campaign at Westgate',
    location: 'Westgate Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 4300,
    feet: '4,300',
    excerpt: 'A six-week festive programme that wrapped Westgate in light and kept retail moving through the longest shopping season of the year.',
    hero: 'Westgate\u2019s Christmas had to be the best in town\u2019s mall circuit: a six-week campaign of light, colour and daily programming that made the mall a festive destination from the first Sunday of December.',
    challenge: 'A six-week festive season demands consistency: the installation had to look fresh on day one and day forty, survive heavy traffic and bad weather, and justify itself to retailers through measurable pass-by and dwell.',
    whatWeDid: prose('', {
      s1: 'We built a full festive wardrobe for the mall: a 14-metre hero tree, ceiling light sculptures over every corridor, window treatments for 22 retailers and a nightly snow event on the hour.',
      s2: 'Daily programming kept the season alive: choir slots, a Santa grotto with 10-minute timed sessions, school performances and two weekend markets interleaved with the retail offer.',
      s3: 'A maintenance rota kept the build performing for the full six weeks, with strike-down cabineted off overnight so trade resumed at 7am sharp.',
      r1: 'Traffic held between 24% and 39% above seasonal baseline across all six weeks, and dwell rose 26% on programme days.',
      r2: 'Twenty-two of the mall\u2019s retailers reported a sales lift during the campaign, averaging 18%.',
    }),
    result: 'Westgate closed the year as the city\u2019s most-visited festive mall, with the grotto and snow show drawing an estimated 31,000 visitors and a programme that felt as strong on its final evening as its first.',
    quote: '"Every evening felt like an event. Retailers were scheduling their best staff for the festive window weeks in advance."',
    facts: [
      ['31,000', 'visitors across the festive season'],
      ['18%', 'average retail sales lift'],
      ['22', 'retail windows dressed'],
      ['6', 'weeks of uninterrupted programming'],
    ],
  },
  {
    databaseId: 1204,
    slug: 'valentines-at-sarit-centre',
    title: "Valentine's Day at Sarit Centre",
    location: 'Sarit Centre, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 3100,
    feet: '3,100',
    excerpt: 'A two-day celebration of connection that filled Sarit\u2019s corridors with couples, friends and an unmistakable buzz.',
    hero: "For Valentine's, Sarit Centre wanted more than red and pink décor: a celebration that made the mall the natural plan for the day, with experiences couples and friends would talk about all weekend.",
    challenge: 'Valentine\u2019s is a make-or-break trading day for retailers but a difficult brief for a mall \u2014 the crowd needs to feel romantic without ever feeling exclusive, and visible without ever feeling inconvenient.',
    whatWeDid: prose('', {
      s1: 'We dressed the atrium as a rose garden with an arch of light, a live florist corner, a slow-dance stage with evening jazz and a photo studio that turned every couple into a editorial-style portrait.',
      s2: 'The day\u2019s programme was planned in tight timed slots so the atrium always had \u2018an act\u2019 without congestion, and events were texted to mall members the night before.',
      s3: 'The full installation was built overnight, ran for two days, and was removed by midnight on the 15th \u2014 leaving the mall pristine for the Saturday trade.',
      r1: 'Traffic rose 29% against the week\u2019s baseline, with the photo studio booked out for 38 hours straight.',
      r2: 'Dwell time grew 21%, and jewellery, fashion and dining tenants each reported their best day of the quarter.',
    }),
    result: 'Sarit\u2019s Valentine\u2019s became the mall\u2019s most-talked-about activation of the year: 3,100 visitors, 1,900 portraits delivered and a social reach of 240,000+ across the two days.',
    quote: '"The studio was the whole plan. We queued twice \u2014 once for the portrait, once because we wanted an evening shot."',
    facts: [
      ['29%', 'traffic lift over two days'],
      ['3,100', 'visitors across the celebration'],
      ['1,900', 'portraits delivered to guests'],
      ['240k', 'social reach in 48 hours'],
    ],
  },
  {
    databaseId: 1205,
    slug: 'easter-at-sarit-centre',
    title: 'Easter at Sarit Centre',
    location: 'Sarit Centre, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 2900,
    feet: '2,900',
    excerpt: 'An egg hunt with 4,000 hidden eggs and a village of workshops that kept Sarit lively from Thursday to Monday.',
    hero: 'For Easter, Sarit turned its lower level into a family village: a hunt, workshops and a live stage that made the long weekend feel like a five-day festival.',
    challenge: 'Easter spans five trading days with very different crowds \u2014 quiet mid-week, frantic on Friday, family-heavy on Sunday and Monday. The programme had to stay full on every one of them.',
    whatWeDid: prose('', {
      s1: 'We hid 4,000 eggs across a mapped hunt zone on the lower level, ran 12 daily workshop sessions (decorating, baking, craft) and staged two live shows a day on the atrium stage.',
      s2: 'The hunt map was updated every afternoon with fresh clusters, so families who came back on Monday found a different game from the one on Friday.',
      s3: 'All workshop stations were built to mall safety standards and staffed by 18 hosts across the weekend, with every session timed and queued by wristband.',
      r1: 'The weekend drew 2,900 visitors \u2014 a 33% lift over the seasonal baseline \u2014 with the lower level abandoning its usual quiet mid-week lull.',
      r2: 'Average dwell stretched 20%, and family restaurant tenants saw queues through the lunch window on all five days.',
    }),
    result: 'The 4,000 hidden eggs became Sarit\u2019s most-shared story, with the hunt map downloaded 6,000+ times and the workshop sessions holding 98% attendance across every slot.',
    quote: '"My kids dragged me back three days in a row because the map had changed. That has never happened to us at a mall."',
    facts: [
      ['33%', 'lift over the weekend baseline'],
      ['4,000', 'eggs across the hunt zone'],
      ['12', 'daily workshop sessions'],
      ['98%', 'session attendance fill'],
    ],
  },
  {
    databaseId: 1206,
    slug: 'valentines-at-southfield-mall',
    title: "Valentine's Day at Southfield",
    location: 'Southfield Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 3500,
    feet: '3,500',
    excerpt: 'A burst of light and sound that made Southfield the city\u2019s boldest Valentine\u2019s destination.',
    hero: 'Southfield wanted a Valentine\u2019s with volume: a dramatic, confident display that stamped the mall as the place to bring someone you love. We gave the atrium its loudest weekend of the year.',
    challenge: 'Working with a large central atrium and a young crowd, Southfield needed an activation that looked spectacular from every floor and scaled from midday\u2019s families to the evening\u2019s couples without a single dead hour.',
    whatWeDid: prose('', {
      s1: 'We hung a canopy of 2,000 lights over the atrium, dressed the mezzanine rails with red installations and built a corner stage that ran duos, DJ sets and spoken-word from noon to 9pm.',
      s2: 'Timed moments every hour \u2014 the light ring, the heart drop, the slow-song slot \u2014 gave visitors reasons to return to the atrium all day.',
      s3: 'The rig was engineered to hang without floor fixings, load-tested ahead of the mall\u2019s opening, and built over two overnight sessions.',
      r1: 'Traffic rose 35% over the weekend, with evening visits surging 48% from 6pm.',
      r2: 'Dwell time climbed 23% and the mall\u2019s cinema and dining anchors reported their best Saturday of the year.',
    }),
    result: 'The 2,000-light canopy became Southfield\u2019s signature image of February, drawing an estimated 3,500 visitors, 1.2m social impressions and a landmark weekend for the mall\u2019s evening economy.',
    quote: '"The light ring moment was genuinely cinematic. People stood and applauded a light show \u2014 at a mall."',
    facts: [
      ['35%', 'weekend traffic lift'],
      ['1.2m', 'social impressions in 48 hours'],
      ['2,000', 'lights across the atrium'],
      ['48%', 'surge in evening visits'],
    ],
  },
  {
    databaseId: 1207,
    slug: 'easter-at-southfield-mall',
    title: 'Easter at Southfield Mall',
    location: 'Southfield Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 4100,
    feet: '4,100',
    excerpt: 'A five-day Easter festival across the concourse \u2014 living characters, workshops and the busiest corridor Southfield has hosted.',
    hero: 'Southfield\u2019s Easter was built as a festival, not a display: five days of living characters, hands-on workshops and a concourse-wide programme that made the long weekend the mall\u2019s biggest of the year.',
    challenge: 'Easter at a young, family-oriented mall needs to hit every shopper type \u2014 the toddler, the teenager, the grandparents \u2014 while keeping the concourse open and trade uninterrupted.',
    whatWeDid: prose('', {
      s1: 'We created a concourse-wide Easter village: a talking tree for story time, a crafts island, a petting pen-in-a-box with careful welfare planning, and a daily parade led by living characters on stilts.',
      s2: 'Activities rotated by the hour so every repeat visit offered something new, and wristband queues kept the village calm even at peak.',
      s3: 'The build was delivered in two overnight installations with the concourse fully cleared for trade by 7am, and safety barriers and walkways planned with the mall operations team.',
      r1: 'The five days drew an estimated 4,100 visitors, a 38% lift over the previous Easter, with the concourse holding its highest footfall since opening.',
      r2: 'Dwell rose 24%, and food court tenants saw a 27% sales lift for the weekend.',
    }),
    result: 'The village ran back-to-back sessions across all five days with zero incidents, and repeat visits made the concourse feel alive from open to close \u2014 the festival Southfield has since made its annual Easter fixture.',
    quote: '"The parade is why we came back on Monday. The kids had told their cousins, and the cousins dragged their parents."',
    facts: [
      ['38%', 'lift over the previous Easter'],
      ['4,100', 'visitors across five days'],
      ['24%', 'concourse dwell increase'],
      ['27%', 'food court sales lift'],
    ],
  },
  {
    databaseId: 1208,
    slug: 'mothers-day-at-southfield-mall',
    title: 'Mothers Day at Southfield',
    location: 'Southfield Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 3000,
    feet: '3,000',
    excerpt: 'A garden of generous gestures \u2014 handwritten notes, portraits and tea \u2014 that made Southfield the day\u2019s most caring address in the city.',
    hero: 'Southfield celebrated Mother\u2019s Day with a garden built from gestures: a wall of handwritten notes, a free portrait studio, and an afternoon tea moment that turned the atrium into the mall\u2019s heart for a full day.',
    challenge: 'Mother\u2019s Day is emotional but fleeting \u2014 a single trading day that demands an installation with dignity, heart and volume, and one that celebrates all the mothers who visit, not just the ones who shop.',
    whatWeDid: prose('', {
      s1: 'We built a central garden with a 10-metre wall of notes where visitors wrote messages to their mothers, a portrait studio with a soft-light set, and an open tea-and-scones moment staged by the atrium caf\u00e9s.',
      s2: 'The day\u2019s rhythm \u2014 morning notes, midday portraits, afternoon tea \u2014 kept the atrium populated from open to close without crowding.',
      s3: 'The build was installed overnight and respectfully struck before Monday trade, with every note collected and delivered to the mall\u2019s charity partner.',
      r1: 'Traffic rose 28% for the day, with 1,600 notes written and more than 900 portraits taken.',
      r2: 'Dwell jumped 24%, and the atrium caf\u00e9s reported their busiest day since opening.',
    }),
    result: 'The note wall became the day\u2019s emotional centrepiece, generating 200,000+ social impressions and turning Southfield\u2019s Mother\u2019s Day into an event families marked by returning the following year.',
    quote: '"We wrote a note at 10am, took a portrait at noon, and came back at 4pm just to read what others had written."',
    facts: [
      ['28%', 'traffic lift on the day'],
      ['1,600', 'notes written for mothers'],
      ['900+', 'portraits delivered'],
      ['24%', 'increase in dwell time'],
    ],
  },
  {
    databaseId: 1209,
    slug: 'fathers-day-at-southfield-mall',
    title: "Father's Day at Southfield",
    location: 'Southfield Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 2600,
    feet: '2,600',
    excerpt: 'A day of bold, playful programming \u2014 karaoke, kart racing and a wall of dad-to-son stories \u2014 that filled Southfield with laughter.',
    hero: "Father's Day often reads as the quieter half of the calendar. Southfield pushed the other way: an activation built on noise, games and shared moments that made dads the centre of the show.",
    challenge: 'The brief was to attract families during a traditionally quiet Sunday \u2014 and to give fathers a genuine reason to bring the family out rather than stay home and watch the match.',
    whatWeDid: prose('', {
      s1: 'We built a Father\u2019s Day festival: a mini-kart circuit on the concourse, a karaoke stage with dad-friendly anthems, a tool-and-tinker workshop for hands-on kids, and a wall where dads shared their best stories.',
      s2: 'Family heats ran all day in timed slots, and the prize ladder (mall vouchers, sponsored prizes) kept repeat visits flowing.',
      s3: 'The concourse layout was planned with the mall team to keep the kart safety zone clear, and the full festival was installed overnight.',
      r1: 'The mall drew 2,600 visitors for the day \u2014 a 31% lift over a normal Sunday \u2014 with the karaoke stage packed from 2pm to close.',
      r2: 'Dwell time stretched 19% and electronics and hobby retailers reported their best Sunday of the year.',
    }),
    result: "The kart circuit became the day's hero, with more than 800 family heats finished, and Southfield turned Father's Day into one of its busiest Sundays of the year.",
    quote: '"Dad lost every heat and sang twice. I do not know this mall without it now."',
    facts: [
      ['31%', 'lift over a normal Sunday'],
      ['800+', 'family heats on the kart circuit'],
      ['2,600', 'visitors across the day'],
      ['19%', 'dwell time increase'],
    ],
  },
  {
    databaseId: 1210,
    slug: 'christmas-at-southfield-mall',
    title: 'Christmas at Southfield Mall',
    location: 'Southfield Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 5600,
    feet: '5,600',
    excerpt: 'A month-long festive spectacle \u2014 a 16-metre tree, an ice rink moment and a grotto \u2014 that made Southfield the family destination of the season.',
    hero: 'Southfield\u2019s Christmas set out to be the biggest in the city\u2019s malls: a month-long programme built around a 16-metre hero tree and the shopping festival that only December can carry.',
    challenge: 'A month-long Christmas campaign over a working mall is a logistics exercise as much as a design brief: it must survive weather, resist wear, entertain every visitor type and keep trading smooth while hosting thousands of daily visits.',
    whatWeDid: prose('', {
      s1: 'We delivered a festival length of actual winter: a 16-metre animated tree, an outdoor winter moment with synthetic snow sessions on the hour, a grotto with 12-minute private sessions and a nightly light showcase timed to retail peak.',
      s2: 'A seasonal retail programme \u2014 shop windows dressed in theme, live choirs, a food hall festive menu and family photo nights \u2014 tied the campaign into the commercial calendar.',
      s3: 'The entire build was engineered, installed and maintained under a 30-day operations plan, with overnight servicing and a strike-down completed in 72 hours before the New Year trade.',
      r1: 'December traffic peaked at 56% over baseline, with the grotto booking out 11 days in advance and the mall holding its busiest quarter ever.',
      r2: 'Dwell time rose 29% on showcase evenings, and tenant sales lifted an average of 21% for the month.',
    }),
    result: 'Southfield closed the year as the family destination of the season: an estimated 45,000 festive visitors, 4,800 grotto bookings and a showcase that tenants now ask for every December.',
    quote: '"The snow hour is a ritual now. The kids time their shopping around it and I schedule my coffee around the light show."',
    facts: [
      ['45,000', 'festive season visitors'],
      ['16m', 'hero tree at the atrium'],
      ['21%', 'average tenant sales lift'],
      ['4,800', 'grotto bookings in December'],
    ],
  },
  {
    databaseId: 1211,
    slug: 'mothers-day-brunch-at-southfield-mall',
    title: 'Mothers Day Brunch at Southfield',
    location: 'Southfield Mall, Nairobi',
    industry: 'Retail & Malls',
    eventType: 'Brand Activation',
    participants: 2100,
    feet: '2,100',
    excerpt: 'A brunch flagship activation \u2014 five live kitchens, a rose wall and 1,100 seats served \u2014 that sold out Southfield\u2019s dining floor twice over.',
    hero: 'Southfield\u2019s flagship Mother\u2019s Day offer was a brunch event built into the mall\u2019s dining floor: a live-kitchen brunch that served 1,100 guests without the mall losing a single trading minute.',
    challenge: 'A high-volume food event inside a working mall pulls two ways: it must feel like a top-grade restaurant experience, and it must respect mall safety, flow and closure times.',
    whatWeDid: prose('', {
      s1: 'We transformed the dining floor into a brunch venue: five live-kitchen islands (roast, waffle, coffee, carving, juice), a 12-metre rose wall and seating for 300 laid across three timed service windows.',
      s2: 'Kitchen equipment was linked to mall power safely via a dedicated distribution plan, and the menus were co-designed with tenants so their kitchens ran the show.',
      s3: 'The two service windows \u2014 10am and 1pm \u2014 delivered 1,100 seats served in a single day, with the entire venue struck down by 6pm.',
      r1: 'The brunch sold out 11 days in advance, drew 2,100 visitors for the day and generated Southfield\u2019s highest single-day food revenue ever.',
      r2: 'Dwell time on the dining floor stretched to an average of 2 hours 10 minutes, and 83% of brunch guests went on to shop after their meal.',
    }),
    result: 'The brunch flagship has become Southfield\u2019s signature Mother\u2019s Day fixture: 1,100 seats served, two sold-out windows and a dining floor that proved it could host an event-grade service without trading a single minute.',
    quote: '"We booked the 1pm window for the whole extended family. It felt like a hotel brunch, but we could shop afterwards without driving anywhere."',
    facts: [
      ['1,100', 'seats served in a single day'],
      ['83%', 'of guests shopped after brunch'],
      ['2hr10', 'average dining-floor dwell'],
      ['11 days', 'sold out in advance'],
    ],
  },
];

export function caseBySlug(slug) {
  return CASE.find((c) => c.slug === slug);
}

export function allCases() {
  return CASE.map((c) => ({ ...c }));
}

export default CASE;