// StillCraft client copy, seeded as file-based content overrides (no DB needed).
// Same shape as DB rows: { el_id, kind, value, orig_html }. Applied via applyOverrides
// (static replace + unique-gated flight patch), so hydration keeps the new copy.
const T = (el_id, value, orig_html) => ({ el_id, kind: 'text', value, orig_html });

// Page-scoped whole-value flight replacements. Applied AFTER flight IA + overrides.
// Safe only when EVERY whole-value occurrence on that page wants the same new value
// (short origs like "Branding" never pass patchFlight's uniqueness gate, so they need this).
export const FLIGHT = {
  '/service/exhibits': [
    [`Exhibits`, `Malls Programming and Retail`],
    [`Branding`, `Eight Years Running Calendars`],
    [`Concept & Design`, `One Team From Planning To The Floor`],
    [`Complex Logistics`, `Built Around Your Tenant Mix`],
    [`Hybrid & Digital Content`, `Every Season Closes With A Report`],
    [`Construction`, `Vendor Managed`],
    [`Technical Production`, `Staffed By Us`],
    [`Guest Experience & Activations`, `Reported Each Season`],
  ],
  '/service/events': [
    [`Events`, `Brands and Corporates`],
    [`Concept & Design`, `Eight Years Delivering`],
    [`Branding`, `Your Strategist Is Your Producer`],
    [`Hybrid & Digital Content`, `Built Around Your Audience`],
    [`Construction`, `Relationships That Compound`],
    [`Technical Production`, `Every Engagement Closes With A Report`],
    [`Complex Logistics`, `Reach And Proximity`],
    [`Guest Experience & Activations`, `One Team Accountable`],
  ],
};

export const CONTENT = {
  '/service/exhibits': [
    T('t-21', `Malls Programming and Retail`, `Exhibits`),
    T('t-24', `One calendar, run for you.`, `We make exhibits`),
    T('t-25', `Not just`, `impossible to`),
    T('t-26', `planned.`, `ignore.`),
    T('t-28', `Entertainment Programmes: recurring activations across Creative Economy, Family Entertainment, STEM and Wellness, sourced, staffed and run by us.`, `We design brand spaces with purpose`),
    T('t-30', `Seasonal Calendar: seven annual moments planned a year ahead of the retail curve.`, `We create experiences that captivate`),
    T('t-32', `Shop Launches and Tenant Support: opening-day moments plus ongoing tenant coordination.`, `We deliver with flawless precision`),
    T('t-33', `The team that stays accountable for the whole calendar.`, `We design exhibit spaces that perform`),
    T('t-34', `Eight Years Running Calendars`, `Branding`),
    T('t-35', `One Team From Planning To The Floor`, `Concept & Design`),
    T('t-36', `Built Around Your Tenant Mix`, `Complex Logistics`),
    T('t-37', `Every Season Closes With A Report`, `Hybrid & Digital Content`),
    T('t-38', `Vendor Managed`, `Construction`),
    T('t-39', `Staffed By Us`, `Technical Production`),
    T('t-40', `Reported Each Season`, `Guest Experience & Activations`),
    T('t-41', `Eight Years Running Calendars`, `Branding`),
    T('t-42', `One Team From Planning To The Floor`, `Concept & Design`),
    T('t-43', `Built Around Your Tenant Mix`, `Complex Logistics`),
    T('t-44', `Every Season Closes With A Report`, `Hybrid & Digital Content`),
    T('t-45', `Vendor Managed`, `Construction`),
    T('t-46', `Staffed By Us`, `Technical Production`),
    T('t-47', `Reported Each Season`, `Guest Experience & Activations`),
    T('t-67', `What The Programme Moves`, `Projects you might also be interested in`),
    T('t-68', `FOOTFALL`, `01`),
    T('t-69', `DWELL TIME`, `02`),
    T('t-70', `TENANT SALES`, `03`),
    T('t-119', `Mall programming answers`, `Experts Answers`),
    T('t-120', `What does StillCraft take off our plate?`, `What does a trade show marketing agency like Iventions deliver at exhibitions?`),
    T('t-121', `Staffing, vendor management and delivery of the full calendar, built to work with your tenant mix. Your team manages the center instead of managing a calendar.`, `A full-service trade show marketing agency designs, produces and manages brand experiences for exhibitions and trade shows. From 3D stand design and graphic production to on-site project management, AV, staffing and activations, every detail is carefully engineered so brands can perform at their best on the show floor.`),
    T('t-122', `How is the calendar built?`, `Is Iventions a trade show marketing company that handles both design and production?`),
    T('t-123', `Every calendar starts with your center's actual traffic patterns and tenant mix. The team that builds it is the same team that staffs and runs it, so nothing gets lost between proposal and delivery.`, `Yes. Iventions is a trade show marketing company with an in-house design and production team. This integrated setup allows full control over quality, timelines and budgets from concept to delivery, keeping the process seamless, efficient and stress-free.`),
    T('t-124', `What are the eight moments?`, `Can exhibition stands be delivered anywhere in Europe?`),
    T('t-125', `New Year, Valentine's, Easter Weekend, Mother's Day, Father's Day, Back to School, Halloween and Christmas -- mapped to the year before the year starts.`, `Yes. While based in Barcelona and London, Iventions delivers projects across Europe. With experience in major exhibition venues, trusted local suppliers and a multilingual team with global know-how, international trade shows are managed smoothly and confidently from start to finish.`),
    T('t-126', `How do we know it worked?`, `What exhibition and trade show services are offered?`),
    T('t-127', `Every season closes with a report. At Galleria Mall, a Father's Day activation delivered a 30% lift in footfall, 22% in dwell time and 17% in tenant sales.`, `Iventions provides a complete end-to-end service covering 3D exhibition stand design, graphic design and branding, stand production and build, audiovisual and technical solutions, hosts and brand ambassadors, interactive activations, logistics, installation, dismantling and on-site project management. All services are integrated under one trade show marketing company to ensure consistency, clarity and quality throughout the project.`),
    T('t-128', `Who runs it on the day?`, `Why choose Iventions as a trade show marketing company?`),
    T('t-129', `We do. StillCraft plans, staffs and runs the entire calendar -- the calendar approved in January is the one delivered in December.`, `Iventions combines strategic thinking, creative design and flawless execution. With in-house capabilities, international experience and a true partnership mindset, the team helps brands stand out, perform and stay memorable at trade shows across Europe.`),
    T('t-130', `Let's take the`, `Let’s build your`),
    T('t-131', `calendar off`, `brand’s next`),
    T('t-132', `your plate`, `showstopper`),
    T('t-133', `Tell us about your shopping mall and what this year's calendar still needs. We'll come back with a plan, and a team that runs it, not just proposes it.`, `From bold ideas to flawless execution, we design exhibit spaces that grab attention and keep it. Let’s create something people won’t just walk past, but talk about.`),
  ],
  '/service/events': [
    T('t-21', `Brands and Corporates`, `Events`),
    T('t-24', `Strategy through delivery.`, `We bring people into`),
    T('t-25', `One team, one brand,`, `the moment, and make`),
    T('t-26', `one bond with your audience.`, `it last.`),
    T('t-28', `REACH:`, `Built on brand,`),
    T('t-29', `Above The Line (ATL) -- campaigns, sponsorships and launch moments at national reach.`, `made to move`),
    T('t-31', `PROXIMITY:`, `Moments that hit`),
    T('t-32', `Below The Line (BTL) -- activations, roadshows and corporate environments in people's hands.`, `different`),
    T('t-34', `CONSULT - PLAN -`, `Precision at any`),
    T('t-35', `PRODUCE - REPORT, one team end to end.`, `scale`),
    T('t-36', `Why Brands Bring Us In`, `We design event spaces that hit every beat`),
    T('t-37', `Eight Years Delivering`, `Concept & Design`),
    T('t-38', `Your Strategist Is Your Producer`, `Branding`),
    T('t-39', `Built Around Your Audience`, `Hybrid & Digital Content`),
    T('t-40', `Relationships That Compound`, `Construction`),
    T('t-41', `Every Engagement Closes With A Report`, `Technical Production`),
    T('t-42', `Reach And Proximity`, `Complex Logistics`),
    T('t-43', `One Team Accountable`, `Guest Experience & Activations`),
    T('t-44', `Eight Years Delivering`, `Concept & Design`),
    T('t-45', `Your Strategist Is Your Producer`, `Branding`),
    T('t-46', `Built Around Your Audience`, `Hybrid & Digital Content`),
    T('t-47', `Relationships That Compound`, `Construction`),
    T('t-48', `Every Engagement Closes With A Report`, `Technical Production`),
    T('t-49', `Reach And Proximity`, `Complex Logistics`),
    T('t-50', `One Team Accountable`, `Guest Experience & Activations`),
    T('t-115', `Brand answers`, `Experts Answers`),
    T('t-116', `What does StillCraft do for brands?`, `What does an event marketing agency like Iventions deliver for brands?`),
    T('t-117', `StillCraft plans a brand's next move and stays on to deliver it, from the boardroom to the ground. No handoffs between strategist and producer, no brief reinterpreted by three vendors. One team, accountable for the relationship your brand builds with its audience.`, `An event marketing agency plans, designs and delivers experiences that connect people with brands in meaningful ways. At Iventions, this means shaping the strategy, creative concept and guest journey, then executing every detail, from venue selection to on-site delivery, so events feel seamless, impactful and memorable.`),
    T('t-118', `What is the ATL and BTL mix?`, `Is Iventions an event management company that handles everything end to end?`),
    T('t-119', `Reach puts the brand in front of the audience that matters at scale: media campaigns, sponsorships, large format and OOH, launch events. Proximity puts it in their hands: experiential activations, roadshows and sampling, in-person promotions, corporate environments.`, `Yes. Iventions is a full-service event management company that takes care of the entire process. From strategy and creative direction to production, logistics, project management and on-site setup, everything is handled under one roof with a single point of contact.`),
    T('t-120', `How does an engagement run?`, `Can an event be delivered anywhere in Europe?`),
    T('t-121', `Consult, then plan, then produce, then report. One team maps media and placements alongside activations and environments around a single idea, and closes with a report on reach, engagement and sentiment.`, `Absolutely. Although based in Barcelona and London, Iventions delivers events across Europe and beyond. With extensive international experience, trusted local suppliers and a multilingual team with global expertise, events are executed smoothly regardless of location.`),
    T('t-122', `Which mix is right for us?`, `What types of events does an event management company like Iventions produce?`),
    T('t-123', `Start with the audience: what they need to feel about the brand, and what it will take to earn that. We recommend ATL, BTL or a blend of both before anything gets built.`, `Iventions delivers a wide range of events, including brand experiences, corporate events, product launches, summits, conferences and immersive experiences. Each project is tailored to the ambition behind it, combining creativity with flawless execution.`),
    T('t-124', `Why bring StillCraft in?`, `Why choose Iventions as an event marketing agency?`),
    T('t-125', `Eight years planning and producing brand marketing under one roof. The idea that gets attention is the same idea that earns trust once your audience is standing in front of you.`, `Iventions combines strategic thinking, creative ambition and meticulous execution. With a partnership mindset, international reach and obsessive attention to detail, the team turns complex ideas into effortless experiences, placing brands and people exactly where they belong: in the spotlight.`),
    T('t-126', `Lets discuss`, `No ordinary events.`),
    T('t-127', `your next`, `Only spotlight`),
    T('t-128', `activation!`, `moments.`),
    T('t-129', `Tell us about your brand and what you're looking to activate. We'll come back with a recommendation on the right mix of reach and proximity, and a team that can deliver both.`, `Every square meter we build is intentional, crafted to impress, engineered to connect, and built for the brands that play on the global stage.`),
  ],
  '/contact': [
    T('t-53', `reaching out we're here, ready to listen. Email info@stillcraftevents.co.ke`, `reaching out we’re here, ready to listen`),
    T('t-54', `Call +254 792 234 337 or +254 755 959 236. Visit Piedmont, 671 Ngong Road, Nairobi, Kenya. Let's connect.`, `and respond with purpose. Let’s connect.`),
  ],
  
  '/privacy-policy': [
    T('t-41', `While using our Website, we may request your personal information, such as your email address, phone number and name. Upon your express acceptance we may use this data to send you newsletters or share marketing materials that may be of interest to you. You can opt out of receiving such communications from us at any time by emailing us at&nbsp;<a data-sc-id="t-42" href="mailto:info@stillcraftevents.co.ke">info@stillcraftevents.co.ke</a>.`, `While using our Website, we may request your personal information, such as your email address, phone number and name. Upon your express acceptance we may use this data to send you newsletters or share marketing materials that may be of interest to you. You can opt out of receiving such communications from us at any time by emailing us at&nbsp;<a data-sc-id="t-42" href="mailto:info@iventions.com">info@iventions.com</a>.`),
    T('t-46', `The entity responsible for processing personal data collected on this website is StillCraft Events Co., with office at Piedmont, 671 Ngong Road, Nairobi, Kenya. You can contact us at +254 792 234 337 or by emailing info@stillcraftevents.co.ke`, `The entity responsible for processing personal data collected on this website is Iventions International Events, S.L.U., identified by tax identification number B65280398 , with address in Av. Diagonal 433, 4-2, Barcelona, Spain. You can contact us at the number +34 933 028 640 or emailing us to info@iventions.com`),
  ],
};
