import { readFile } from 'node:fs/promises';
import { getOverrides, applyOverrides } from './overrides.mjs';
import { getBrand, applyBrand, applyNav, applyServiceCardsFix, applyContentFlight, stripThirdParty, removeBadges } from './transform.mjs';
const ROOT = 'dist';
let html = await readFile(ROOT + '/index.html', 'utf8');
const key = '/';
const step = (label) => {
  const re = /<h4 data-sc-id="(t-\d+)" class="css-hj2ayb">([^<]*)<\/h4>/g;
  const out = [];
  let m;
  while ((m = re.exec(html))) out.push(`${m[1]}=${JSON.stringify(m[2])}`);
  console.log(label.padEnd(20), out.join('  '));
};
step('raw');
html = stripThirdParty(html);
html = removeBadges(html);
html = applyBrand(html, await getBrand());
html = applyNav(html, key);
step('after applyNav');
const overrides = await getOverrides(key);
for (const o of overrides) console.log('  db ov:', o.idx, o.tag, o.kind, JSON.stringify(o.orig_html), '->', JSON.stringify(o.value));
html = applyOverrides(html, overrides, {});
step('after db overrides');
console.log('  MaliCalProg count:', html.split('Mall Calendar Programming').length - 1);
html = applyServiceCardsFix(html, key);
step('after svcCardsFix');
html = applyContentFlight(html, key);
step('after contentFlight');